# Generated by Django 4.2.2 on 2023-06-22 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customers_delete_customer_remove_product_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
